Adicionado partes da estratégia autonoma
GabrielSTX/Trainee-Rinobot pull request #5
Opened 2022-12-12 23:31 UTC by GabrielSTX

fix https://github.com/GabrielSTX/Trainee-Rinobot/issues/3

2022-12-13 14:08 UTC, jgabriellacerda commented on src/strategy.cpp
> +    Move* move = new Move(left_power, right_power, time_ms);
Na AutoStrategy não precisa usar a classe Move, ela é mais pra InitialStrategy. Você pode alterar o power do motor diretamente na AutoStrategy.

2023-01-30 22:44 UTC, GabrielSTX commented
fix https://github.com/GabrielSTX/Trainee-Rinobot/issues/4

2023-01-31 22:44 UTC, jgabriellacerda commented on src/robot.cpp
>      this->vision.updateEnemyPosition(this->front_sensor, this->full_left_sensor, this->full_right_sensor, this->left_sensor, this->right_sensor);
Faltou atualizar os sensores antes de atualizar a visão

2023-01-31 22:47 UTC, jgabriellacerda commented on src/strategy.cpp
> +    delay(this->time_ms);
Não é uma boa pratica usar delay dentro de algum método pq o resto do código para de ser atualizado. Você pode monitorar o tempo que a movimentação está sendo executada calculando a diferença do millis pro start_time_ms

2023-01-31 22:49 UTC, jgabriellacerda commented on src/strategy.cpp
> +    for(Move x : moves){
Se você usar um for no InitialStrategy o resto do código para de atualizar, vc pode usar o retorno do Move::update pra saber se as movimentações acabaram, parar de executar a estratégia inicial e passar a executar a autônoma

2023-02-10 15:05 UTC, jgabriellacerda requested changes

2023-02-10 15:05 UTC, jgabriellacerda commented on src/strategy.cpp
> +    this->current_move.update(left_motor, right_motor);
O que acontece nesse ponto se após a linha:
 `this->moves.pop_front();`
O lista "this->moves" estiver vazia?

2023-02-10 15:05 UTC, jgabriellacerda commented on src/strategy.cpp
> +    this->started = true;
O "Move" só deve ser considerado "started" após a primeira chamada do método "Move::update"

2023-02-10 15:05 UTC, jgabriellacerda commented on src/strategy.cpp
> +    this->start_time_ms = millis();
O "start_time_ms" é o instante em que ocorre a primeira chamada do método "Move::update".

2023-02-10 15:06 UTC, jgabriellacerda commented
Faltou implementar algumas coisas da issue https://github.com/GabrielSTX/Trainee-Rinobot/issues/6

2023-02-10 16:25 UTC, jgabriellacerda approved these changes

2023-02-10 16:26 UTC, merged